###############################################################################################
# Yaml File to declare the User Credentials and the list of Network Devices                   #
# As a optional feature, you can print result in the CLI with the boolean variable 'PrintCLI' #
###############################################################################################

# Authentication variables for SSH
Credentials:

    username : ""     # Username for SSH Authentication
    password : ""     # Password for the Username

# Variable to print result in the CLI
PrintCLI: True

# Network Device FQDN or IP Address
NetworkDevice:
    - router.1.fqdn
    - router.2.fqdn
    - router.3.fqdn
    - router.4.fqdn
