###############################################################################################
# Yaml File to declare the User Credentials and the list of Network Devices                   #
# As a optional feature, you can print result in the CLI with the boolean variable 'PrintCLI' #
###############################################################################################

# Authentication variables for SSH
Credentials:

    username : "e058386"     # Username for SSH Authentication
    password : "ZDA139x8"    # Password for the Username

# Variable to print result in the CLI
PrintCLI: True

# Network Device FQDN or IP Address
NetworkDevice:
    - nextc1cldwp1.igrupobbva
    - nextc1cldwp2.igrupobbva
    - nexvagcdlwp1.igrupobbva
    - nexvagcdlwp2.igrupobbva
